#!/bin/bash
if [[ "$1" == 'debug'  ]]; then set -x;		_DEBUG=$1; shift; fi
if [[ "$1" == 'debug2' ]]; then set -xvT;	_DEBUG=$1; shift; fi
if [[ "$1" == 'trace'  ]]; then 		_TRACE=$1; shift; fi
####################################################################
PROC_START=`date +%s%N`
#------------------------
REALPATH=`realpath $0`
WHERE=`dirname $REALPATH`
ME=`basename $REALPATH`
cd $WHERE
. ../../system.conf
. ../../watchermap.conf
. ../../common.conf
. ../../common.bashlib
. ../../api/bash/nft.bashlib
#------------------------
. WatchMX.conf

trap cleanup    0 1 2 9 15

cleanup() {
        PROC_END=`date +%s%N`
        PROC_TIME=`echo "scale=3; ($PROC_END - $PROC_START)/10^6" | bc`
        logger "$ME[$$]: Finished: $PROC_TIME ms'"
        printf  " » %-15s ... finished in %8.2f ms\n" $ME $PROC_TIME
}


#--------------- Main -------------------
LOADER=MX
LOADFILE=$POOL/nftset.Loadfile-$LOADER

log "$ME started loading from $DB ..."

#
# Read the mailhogs.db and fill the load file 
#
### Remove trash at first ...
$SQL "delete from mailhogs where IP='' or IP='unknown';"

>$LOADFILE
MAILHOGS=`$SQL "select IP,type,class from mailhogs where state='DROP' order by IP;"`

echo "$MAILHOGS" |\
awk 	-v loadfile=$LOADFILE 		\
	-v setname=$MYSET 		\
	-v settyp="$SETTYP" 		\
	-v setopts="$SETOPTS" 		\
	-v basetable="$NFT_BASE_TAB" '
BEGIN   {}
        {
                split ($0,parts,"|")
                mailhogs[parts[1]]=parts[2]","parts[3]
        }
END     {
#	printf "-exist create %s %s %s\n", setname, settype, setopts > loadfile
        printf "add set %s %s {type %s; %s}\n", basetable, setname, settyp, setopts > loadfile

        for (mailhog in mailhogs) {
                CLASS=mailhogs[mailhog]
#		COMMENT="DB,"CLASS
		COMMENT=setname","CLASS
		if ( mailhog != "" )
		#	printf "add %s %s comment \"%s\"\n", setname, mailhog,COMMENT >> loadfile
			printf "add element %s %s {%s comment \"%s\"}\n", basetable, setname, mailhog, COMMENT >> loadfile
	}
}
'

have_it=`nft_sets | grep $MYSET`

if [ -z "$have_it" ]
then nft_mkset $MYSET "$SETTYP" "$SETOPTS"	
fi

nft_flush_set $MYSET
nft -f $LOADFILE

log "$ME finished loading ..."
